{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.engine.kube.ci
  labels:
    {{- include "kubeci-engine.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: workflow.validators.engine.kube.ci
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.engine.kube.ci/v1alpha1/workflows
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - engine.kube.ci
    apiVersions:
    - "*"
    resources:
    - workflows
  failurePolicy: Fail
- name: workplan.validators.engine.kube.ci
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.engine.kube.ci/v1alpha1/workplans
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - UPDATE
    apiGroups:
    - engine.kube.ci
    apiVersions:
    - "*"
    resources:
    - workplans
  failurePolicy: Fail
{{ end }}
